### DISCUSSION TITLE
Auto deploy branch to shinyapps.io

### DISCUSSION THREAD

**Discussion by KoderKow** [ThinkR-open/golem#673] [Q&A]
Hello!

Recently at work I have incorporated [Git-Backed Content](https://docs.rstudio.com/connect/user/git-backed/#:~:text=Content%20may%20be%20deployed%20to,workflows%20and%20continuous%20deployment%20automation.) which deploys new code to RSConnect when new code is detected. I love the idea and was wondering if this is possible with GitHub Actions and shinyapps.io?

I was going through [this blog post](https://www.r-bloggers.com/2021/02/deploy-to-shinyapps-io-from-github-actions/) and was trying to incorporate it with my golem app. The problem is I am not familiar with GitHub actions or docker to adjust the code given so my effort ended in errors. I tried using the docker file golem generates (golem::add_dockerfile()) with modifications to run the deploy script (from the blog post) but run into the remotes package not available in the GitHub action. I looked at the docker file from the blog post and assumed it isn't set for a golem app. 

Does this seem plausible? Is it useful? Would love to hear the pros/cons of trying to implement this!

**Comment by KoderKow** [comment]
Classic. Figured it out after posting. Found a post on [RStudio Community](https://community.rstudio.com/t/deploying-shiny-app-with-github-actions/78436) and modified it. Would this be useful as a function within golem? Perhaps `golem::add_shinyappsio_auto_deploy_file()`? This may work with other platforms such as RSC as well.

Here's the yml:

```yml
on: [push, pull_request]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rsconnect"), type = "binary")
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
      - name: Push to shinyapps.io
        run: |
          rsconnect::setAccountInfo(name="${{secrets.SHINY_ACC_NAME}}", token="${{secrets.TOKEN}}", secret="${{secrets.SECRET}}")
          rsconnect::deployApp(appName = 'dinnR')
        shell: Rscript {0}
```
