### DISCUSSION TITLE
Database path in dev and production

### DISCUSSION THREAD

**Discussion by pythiantech** [ThinkR-open/golem#708] [Q&A] [answered]
For my `{golem}`  based Shiny app, I am defining the path to my database in `golem-config.yml` file as this path is different in dev and production:
```
default:
  golem_name: TMSGolem
  golem_version: 0.0.0.9000
  app_prod: no
  dbpath: data/ctms.db
production:
  app_prod: yes
  dbpath: /home/data/ctms.db
dev:
  golem_wd: /Users/dhirajkhanna/Documents/shiny_experiments/TMSGolem
```
Thereafter I am defining a function in `golem_utils_server.R` :

```
#Pool Handler
pool <- pool::dbPool(
  drv = RSQLite::SQLite(),
  dbname = get_golem_config('dbpath') 
)
```

While this works, is it the right way to define the path?
Secondly, how do I switch over to config values for ‘production’?

In `run_dev.R`, I tried `options(golem.app.prod = TRUE)` but the `dbpath` picked up is still what is there in the default configuration.

I am also thinking perhaps making an entry like this in the Dockerfile would work?
`CMD R -e "Sys.setenv('R_CONFIG_ACTIVE' = 'production')"`
Haven't tested this as I don't have access to the production server yet.

And thanks again for making such a terrific package!

**Comment by ColinFay** [comment, marked as answer]
Hey @pythiantech, 

Side note before answering: thanks for the positive feedback 🤘. That always means a lot to us. 

Side note two: as of golem v0.3.1, you can use the `GOLEM_CONFIG_ACTIVE` env var if you really want to focus on using the `golem-config` file, without conflicting with potential `{config}` elements (notably on RStudio Connect). 

1. Yes, this is the correct way to do, you can find an example of this behavior here : 
- https://engineering-shiny.org/golem.html#manipulating-golem-config.yml 

As you can see, the behavior is the following one: 

```r
# default 
get_golem_config(
  "MONGODBURL"
)
[1] "localhost"

# Changing the config ENV_VAR
Sys.setenv("GOLEM_CONFIG_ACTIVE" = "production")
get_golem_config(
  "MONGODBURL"
)
[1] "0.0.0.0"
```

A full example of a working app playing with `GOLEM_CONFIG_ACTIVE` can be found here https://github.com/ColinFay/golemexamples/tree/master/golemyamlapps

1.5 side note, you should define the Pool inside another function, so that the pool can be created at runtime, something like :

```r
make_pool <- function(){
	pool::dbPool(
		drv = RSQLite::SQLite(),
		dbname = get_golem_config('dbpath') 
	)
}
```

Then in app_server : 

```r
app_serve <- function(){
	pool <- make_pool()
}
```

That way, the pool will be created __at runtime__ not when compiling the package. 
see https://github.com/ThinkR-open/golem/issues/552#issuecomment-743184765 for a discussion around this. 

2. Yes, that's a way to do it, by defining `Sys.setenv('GOLEM_CONFIG_ACTIVE' = 'production');` just before the `run_app()`. You can also play with `.Renviron` files or the `{dotenv}` package, but to be honest for just one env_var, you can definitely do it with `Sys.setenv`.

Cheers, 
Colin

**Reply by pythiantech** [reply]
Thanks @ColinFay for your answer and the additional side not on the `make_pool()` function. Much appreciated, merci beaucoup!

**Comment by pythiantech** [comment]
Hello @ColinFay, I finally got access to the production server and was hence able to test my Docker image. Unfortunately it fails as the `production` configuration is not set. As you suggested, this is what I did in my `Dockerfile`:

```
RUN mkdir /home/data
COPY data /home/data
RUN mkdir /build_zone
ADD . /build_zone
WORKDIR /build_zone
RUN R -e 'remotes::install_local(upgrade="never")'
RUN rm -rf /build_zone
EXPOSE 80
CMD R -e "options('shiny.port'=80,shiny.host='0.0.0.0');Sys.setenv('GOLEM_CONFIG_ACTIVE' = 'production');TMSGolem::run_app()"
```
However, with this, the default configuration gets picked up and not the production which is defined as follows in `golem-config.yml`:

```
default:
  golem_name: TMSGolem
  golem_version: 0.0.0.9000
  app_prod: no
  dbpath: data/ctms.db
  vectorpath: data/course_vectors/
  studentpics: data/student_pics2/
production:
  app_prod: yes
  dbpath: /home/data/ctms.db
  vectorpath: /home/data/course_vectors/
  studentpics: /home/data/student_pics2/
dev:
  golem_wd: /Users/dhirajkhanna/Documents/shiny_experiments/TMSGolem

```
The workaround that I am using currently (and I think is quite sloppy) is to have `Sys.setenv('GOLEM_CONFIG_ACTIVE' = 'production')` included in `golem_utils_server.R`. This works, but I have to change this every time I want to build a Docker image.

Can you please tell me what am I doing wrong here?
